import { MODULE, AUTHORISATION_ORG } from '../constants';
export const DETAIL = 'DETAIL';
export const OVERVIEW = 'OVERVIEW';

export const OVERVIEW_ACTIONS = {
    FETCH: `${MODULE}/${AUTHORISATION_ORG}/${OVERVIEW}/FETCH`,
};

export const DETAIL_ACTIONS = {
    FETCH: `${MODULE}/${AUTHORISATION_ORG}/${DETAIL}/FETCH`,
};

export const AUTHORISATION_ORG_ACTIONS = {
  OVERVIEW: OVERVIEW_ACTIONS,
  DETAIL: DETAIL_ACTIONS
};
