export const TYPE_GROUPS = 'GROUPS';
export const TYPE_DASHBOARDMONITOR = 'DASHBOARDMONITOR';
export const TYPE_MONITOR = 'MONITOR';

export const ACTIONS = {
  FETCH_GROUPS: `${TYPE_GROUPS}/FETCH_ALL`,
  FETCH_DASHBOARDMONITOR: `${TYPE_DASHBOARDMONITOR}/FETCH`,
  FETCH_MONITOR: `${TYPE_MONITOR}/FETCH`,
};
