export const TYPE_LIST = 'RECYCLING_PROCESSES';
export const TYPE_DETAIL = 'RECYCLING_PROCESS';

export const ACTIONS = {
  FETCH_ALL: `${TYPE_LIST}/FETCH`,
  FETCH: `${TYPE_DETAIL}/FETCH`,
  CREATE: `${TYPE_DETAIL}/CREATE`,
  ADD_TO_LIST: `${TYPE_LIST}/CREATE`,
  UPDATE: `${TYPE_DETAIL}/UPDATE`,
  ACTIVATE: `${TYPE_DETAIL}/ACTIVATE`,
  DEACTIVATE: `${TYPE_DETAIL}/DEACTIVATE`,
  REMOVE_FROM_LIST: `${TYPE_LIST}/REMOVE`,
};
