version: '3.1'
services:
  app:
    container_name: nodejs-boilerplate-${NODE_ENV}
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV}
    restart: always
    command: pm2-runtime start pm2.config.js --env ${NODE_ENV}
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=${NODE_ENV}
