version: '3.4'
services:
  server:
    build:
      context: ./server
      args:
        - NODE_ENV=${NODE_ENV}
    container_name: server-${NODE_ENV}
    command: pm2-runtime start pm2.config.js --env ${NODE_ENV}
    restart: always
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=${NODE_ENV}
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.server
    container_name: client-${NODE_ENV}
    restart: always
    ports:
      - 80:80
    environment:
      - NODE_ENV=${NODE_ENV}
    links:
      - server
