version: '3.2'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
      args:
        - NODE_ENV=${NODE_ENV}
    container_name: server-${NODE_ENV}
    command: pm2-runtime start pm2.config.js --env ${NODE_ENV}
    restart: always
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=${NODE_ENV}
  client:
    build:
      args:
        - buildenv=${NODE_ENV}
      context: ./client
      dockerfile: Dockerfile.server
    container_name: client-${NODE_ENV}
    restart: always
    ports:
      - 4350:4350
    environment:
      - NODE_ENV=${NODE_ENV}
    links:
      - server
  mongodb-rare:
    image: mongo:4.0.4-xenial
    container_name: rare-mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27011:27017
    volumes:
      - ./data/db:/data/db:delegated
    command: mongod --smallfiles --logpath=/dev/null # --quiet
