version: '3.2'
services:
  server:
    build:
      context: ./server
      args:
        - NODE_ENV=local
    container_name: rare-server
    command: sh -c "/wait && /node_modules/.bin/nodemon --inspect=0.0.0.0:5858"
    ports:
      - 4351:4351
      # Debug port
      - 5858:5858
    volumes:
      - ./server:/app:delegated
      - notused:/app/node_modules
    environment:
      - WAIT_HOSTS=mongodb-rare:27017
      - SERVICE_PORTS=4350
      - NODE_ENV=local
    depends_on:
      - mongodb-rare
  client:
    build:
      context: ./client
    container_name: rare-client
    ports:
      - 4350:4350
    volumes:
      - ./client:/app:delegated
      - /app/node_modules
    links:
      - selenium-chrome-standalone
      - server
    depends_on:
      - selenium-chrome-standalone
  mongodb-rare:
    image: mongo:4.0.4-xenial
    container_name: rare-mongodb
    environment:
      - MONGO_DATA_DIR=/server/data/db
      - MONGO_LOG_DIR=/server/dev/null
    ports:
      - 27011:27017
    volumes:
      - ./server/data/db:/server/data/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  selenium-chrome-standalone:
    ports:
     - 44444:4444
    image: "selenium/standalone-chrome"
volumes:
    notused:
