version: '3.1'
services:
  app:
    image: app-image
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        # Default docker-compose pinpoints to local environment
        - NODE_ENV=local
    container_name: rare
    environment:
        - WAIT_HOSTS=mongodb-rare:27017
        - SERVICE_PORTS=4350
    command: sh -c "/wait && ../node_modules/.bin/nodemon --inspect=0.0.0.0:5856"
    ports:
      # App port
      - 4350:4350
      # Debug port
      - 5856:5856
    volumes:
      # Delegated option for faster mounted volumes
      - ./app:/app/app:delegated
      - ./config:/app/config:delegated
      - ./angular.json:/app/angular.json
      # Because `npm install`
      - ./package.json:/package.json
      - ./package-lock.json:/package-lock.json
      # Block local modules
      - /app/node_modules/
    depends_on:
      - mongodb-rare
  fe:
    image: app-image
    environment:
        - WAIT_HOSTS=mongodb-rare:27017, app:4350
        - SERVICE_PORTS=4350
    container_name: rare-fe
    command: sh -c "/wait && ../node_modules/.bin/ng serve --host=0.0.0.0"
    port@s:
      # App port
      - 4351:4350
    volumes:
      # Delegated option for faster mounted volumes
      - ./src:/app/src:delegated
      # Because `npm install`
      - ./package.json:/package.json
      - ./package-lock.json:/package-lock.json
      # Block local modules
      - /app/node_modules/
    depends_on:
      - mongodb-rare
      - app
  mongodb-rare:
    image: mongo:latest
    container_name: "mongodb-rare"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27011:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
