FROM node:carbon-alpine

RUN mkdir -p /app

WORKDIR /
COPY package.json package-lock.json* /
RUN npm install

ENV PATH /node_modules/.bin:$PATH

WORKDIR /app
COPY . /app

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait

CMD [ "node", "index.js" ]
