version: '3.1'
services:
  app:
    container_name: rare-${NODE_ENV}
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV}
    restart: always
    ports:
      - 80:80
    environment:
      - NODE_ENV=${NODE_ENV}
