export const MODULE = 'MANAGE_USERS';
export const OVERVIEW = 'OVERVIEW';
export const DETAIL = 'DETAIL';
export const REQUESTS = 'REQUESTS';

export const OVERVIEW_ACTIONS = {
  FETCH: `${MODULE}/${OVERVIEW}/FETCH`,
  CLEAR: `${MODULE}/${OVERVIEW}/CLEAR`,
};

export const DETAIL_ACTIONS = {
  FETCH: `${MODULE}/${DETAIL}/FETCH`,
  CLEAR: `${MODULE}/${DETAIL}/CLEAR`,
  UPDATE: `${MODULE}/${DETAIL}/UPDATE`,
};

export const REQUESTS_ACTIONS = {
  FETCH_PENDING_REQUESTS: `${MODULE}/${REQUESTS}/FETCH_PENDING_REQUESTS`,
};

export const ACTIONS = {
  OVERVIEW: OVERVIEW_ACTIONS,
  DETAIL: DETAIL_ACTIONS,
  REQUESTS: REQUESTS_ACTIONS,
};
