export const TYPE_LIST = 'RECYCLING_PARTNERS';
export const TYPE_DETAIL = 'RECYCLING_PARTNER';

export const ACTIONS = {
  ADD_TO_LIST: `${TYPE_LIST}/ADD_TO_LIST`,
  REMOVE_FROM_LIST: `${TYPE_LIST}/REMOVE_FROM_LIST`,
  FETCH_ALL: `${TYPE_LIST}/FETCH`,

  FETCH: `${TYPE_DETAIL}/FETCH`,
  UPDATE: `${TYPE_DETAIL}/UPDATE`,
  ACTIVATE: `${TYPE_DETAIL}/ACTIVATE`,
  DEACTIVATE: `${TYPE_DETAIL}/DEACTIVATE`,
};
