export const TYPE = 'ENTITIES';

export const ACTIONS = {
  NORMALIZE_OVERWRITE: `${TYPE}/NORMALIZE_OVERWRITE`,
  NORMALIZE_MERGE: `${TYPE}/NORMALIZE_MERGE`,
  PATCH: `${TYPE}/PATCH`,
  REMOVE: `${TYPE}/REMOVE`,
};
