version: 2
jobs:
  test-client:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Build, up & test
          command: |
            docker-compose build
            docker-compose up -d && docker-compose exec client npm run test:ci
            docker-compose down

  deploy-develop:
    machine:
      enabled: true
    environment:
      SERVER: "198.211.119.171"
    steps:
      - run: ssh-keyscan $SERVER >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "bf:4d:de:df:60:0e:c7:aa:95:4d:3d:98:d2:d6:e8:49"
      - run:
          name: Deploy to development server
          command: |
            ssh shd@$SERVER "NODE_ENV=development" bash -c '
            cd /var/www/rare_app_nodejs
            git checkout .
            git checkout development
            git pull
            docker-compose down
            NODE_ENV=development docker-compose -f docker-compose.yml -f docker-compose.ci.yml up --build -d'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test-client
      - deploy-develop:
          requires:
            - test-client
          filters:
            branches:
              only: development
