version: 2
jobs:
  test-client:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

  deploy-develop:
    machine:
      enabled: true
    environment:
      SERVER: "198.211.119.171"
    steps:
      - run: ssh-keyscan $SERVER >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "bf:4d:de:df:60:0e:c7:aa:95:4d:3d:98:d2:d6:e8:49"
      - run:
          name: Deploy to development server
          command: |
            ssh shd@$SERVER "NODE_ENV=development" bash -c '
            cd /var/www/rare_app_nodejs
            git checkout .
            git checkout development
            git pull
            docker-compose down
            NODE_ENV=development docker-compose -f docker-compose.yml -f docker-compose.ci.yml up --build -d'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test-client
      - deploy-develop:
          requires:
            - test-client
          filters:
            branches:
              only: development
