import { MODULE, DETAIL, RECYCLING_PROCESSES } from '../../constants';

export const DETAIL_ACTIONS = {
  FETCH: `${MODULE}/${RECYCLING_PROCESSES}/${DETAIL}/FETCH`,
  CLEAR: `${MODULE}/${RECYCLING_PROCESSES}/${DETAIL}/CLEAR`,
  UPDATE: `${MODULE}/${RECYCLING_PROCESSES}/${DETAIL}/UPDATE`,
};
