export const TYPE_USER = 'AUTH_USER';

export const ACTIONS = {
  LOGIN_USER: `${TYPE_USER}/LOGIN`,
  REGISTER_USER: `${TYPE_USER}/REGISTER`,
  FETCH_USER: `${TYPE_USER}/FETCH`,
  CLEAR_USER: `${TYPE_USER}/CLEAR`,
};
