export const TYPE_USER = 'AUTH_USER';
export const TYPE_REGISTER = 'AUTH_REGISTER';

export const ACTIONS = {
  LOGIN_USER: `${TYPE_USER}/LOGIN`,
  REGISTER_USER: `${TYPE_REGISTER}/REGISTER`,
  FETCH_USER: `${TYPE_USER}/FETCH`,
  CLEAR_USER: `${TYPE_USER}/CLEAR`,
  UPDATE_COMPANY: `${TYPE_USER}/UPDATE_COMPANY`
};
