export const MODULE = 'MANAGE_COMPANIES';
export const OVERVIEW = 'OVERVIEW';
export const DETAIL = 'DETAIL';

export const OVERVIEW_ACTIONS = {
    FETCH_ALL: `${MODULE}/${OVERVIEW}/FETCH_ALL`,
    FETCH: `${MODULE}/${OVERVIEW}/FETCH`,
    CLEAR: `${MODULE}/${OVERVIEW}/CLEAR`,
    ADD_TO_LIST: `${MODULE}/${OVERVIEW}/ADD_TO_LIST`,
    REMOVE_FROM_LIST: `${MODULE}/${OVERVIEW}/REMOVE_FROM_LIST`,
};

export const DETAIL_ACTIONS = {
    FETCH: `${MODULE}/${DETAIL}/FETCH`,
    CLEAR: `${MODULE}/${DETAIL}/CLEAR`,
    UPDATE: `${MODULE}/${DETAIL}/UPDATE`,
    ACTIVATE: `${MODULE}/${DETAIL}/ACTIVATE`,
    DEACTIVATE: `${MODULE}/${DETAIL}/DEACTIVATE`,
};

export const ACTIONS = {
    OVERVIEW: OVERVIEW_ACTIONS,
    DETAIL: DETAIL_ACTIONS,
};
