import { _ as ngxExtract } from '@biesbjerg/ngx-translate-extract/dist/utils/utils';

export const METHODS_OF_PROCESSING = [{
  value: 'NOT-APPLICABLE',
  label: ngxExtract('CONSTANTS.METHODS-OF-PROCESSING.NOT-APPLICABLE')
}, {
  value: 'HYDROMETALLURGY',
  label: ngxExtract('CONSTANTS.METHODS-OF-PROCESSING.HYDROMETALLURGY')
}, {
  value: 'MECHANICAL',
  label: ngxExtract('CONSTANTS.METHODS-OF-PROCESSING.MECHANICAL')
}, {
  value: 'MECHANICAL-HYDROMETALLURGY',
  label: ngxExtract('CONSTANTS.METHODS-OF-PROCESSING.MECHANICAL-HYDROMETALLURGY')
}, {
  value: 'MECHANICAL-METALLURGICAL',
  label: ngxExtract('CONSTANTS.METHODS-OF-PROCESSING.MECHANICAL-METALLURGICAL')
}, {
  value: 'PYROMETALLURGY',
  label: ngxExtract('CONSTANTS.METHODS-OF-PROCESSING.PYROMETALLURGY')
}, {
  value: 'VACUUM-THERMAL-PROCESS',
  label: ngxExtract('CONSTANTS.METHODS-OF-PROCESSING.VACUUM-THERMAL-PROCESS')
}];
